request:
  headers:
    Content-Type: "application/json"
    Bearer: "dslkfjsdlkjfdslkjffdslkj"
routes:
  - path: /foo/bar
    methods:
      get:
        200:
          body:
            TotalRecordsFound: 204
            Offset: 0
            RecordsReturned: 10
        400:
          body:
            error: 400
            message: Failed
      put:
        foo: bar
  - path: /foo/{id}/wibble
    parameters:
      id: '\d+'
    methods:
      get:
        200:
          body:
            TotalRecordsFound: 204
            Offset: 0
            RecordsReturned: 10
        404:
