type: rest
route:
  get:
    path: /foo/bar
    request:
      headers:
        Content-Type: "application/json"
        ApiToken: "dslkfjsdlkjfdslkjffdslkj"
    response:
      Content-Type: "application/json; charset=utf-8"
    pass:
      request:
        body:
          foo: bar
      response:
        body:
          SearchSummary:
            TotalRecordsFound: 204
            Offset: 0
            RecordsReturned: 10
